-- Run this SQL in your Supabase SQL Editor to enable the new secure admin settings

-- Create settings table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.settings (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS (Row Level Security) but only allow read/write from service role (our server)
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- No public access policies needed since we use the service_role key on the server

-- Insert default admin password (admin)
-- The hash is generated by bcrypt for the word 'admin'
INSERT INTO public.settings (key, value)
VALUES ('admin_password', '$2b$10$fj6TXCrf9O48g/nGXr47vOnms8vb7NpubYIJGcEn8.tSEg05fG2eO')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
